repository:
  # See https://developer.github.com/v3/repos/#edit for all available settings.

  # The name of the repository. Changing this will rename the repository
  name: Sokol.NET

  # A short description of the repository that will show up on GitHub
  description: .NET wrapper for https://github.com/floooh/sokol

  # A URL with more information about the repository
  # homepage: https://example.github.io/

  # Either `true` to make the repository private, or `false` to make it public.
  private: false

  # Either `true` to enable issues for this repository, `false` to disable them.
  has_issues: true

  # Either `true` to enable the wiki for this repository, `false` to disable it.
  has_wiki: false

  # Either `true` to enable downloads for this repository, `false` to disable them.
  has_downloads: true

  # Updates the default branch for this repository.
  default_branch: develop

  # Either `true` to allow squash-merging pull requests, or `false` to prevent
  # squash-merging.
  allow_squash_merge: true

  # Either `true` to allow merging pull requests with a merge commit, or `false`
  # to prevent merging pull requests with merge commits.
  allow_merge_commit: true

  # Either `true` to allow rebase-merging pull requests, or `false` to prevent
  # rebase-merging.
  allow_rebase_merge: true

# Labels: define labels for Issues and Pull Requests
labels:
  - name: bug
    color: '#d73a4a'
    description: 'Something isn't working (used on an issue)'
  - name: documentation
    color: '#0075ca'
    description: 'Improvements or additions to documentation (used on an issue or pull request)'
  - name: duplicate
    color: '#cfd3d7'
    description: 'Already exists (used on an issue or pull request)'
  - name: enhancement
    color: '#a2eeef'
    description: 'New feature or request (used on an issue)'
  - name: feature
    color: '#ce8de0'
    description: 'Added enhancement (used on a pull request)'
  - name: fix
    color: '#96ff3a'
    description: 'Fixes a bug (used for a pull request)'
  - name: good first issue
    color: '#7057ff'
    description: 'Good starting point for newcomers (used on an issue)'
  - name: help wanted
    color: '#008672'
    description: 'Contributors welcome! (used on an issue)'
  - name: question
    color: '#d876e3'
    description: 'Further information is requested (used on an issue)'
  - name: wontfix
    color: '#ffffff'
    description: 'This will not be worked on (used on an issue)'

branches:
  - name: develop
    # https://developer.github.com/v3/repos/branches/#update-branch-protection
    # Branch Protection settings. Set to null to disable
    protection:
      # Required. Require at least one approving review on a pull request, before merging. Set to null to disable.
      required_pull_request_reviews:
        # The number of approvals required. (1-6)
        required_approving_review_count: 1
        # Dismiss approved reviews automatically when a new commit is pushed.
        dismiss_stale_reviews: true
        # Blocks merge until code owners have reviewed.
        require_code_owner_reviews: true
      # Required. Require status checks to pass before merging. Set to null to disable
      required_status_checks:
        # Required. Require branches to be up to date before merging.
        strict: true
        # Required. The list of status checks to require in order to merge into this branch
        contexts: ['Build', 'Deploy']
      # Required. Enforce all configured restrictions for administrators. Set to true to enforce required status checks for repository administrators. Set to null to disable.
      enforce_admins: true
      # Required. Restrict who can push to this branch. Team and user restrictions are only available for organization-owned repositories. Set to null to disable.
      restrictions:
        apps: []
        users: []
        teams: []    