os: osx
language: csharp
mono: none
dotnet: 3.0
git:
  quiet: true
  depth: 1
branches:
  only:
  - master
env:
  - DOTNET_CLI_TELEMETRY_OPTOUT=true
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
script:
 - dotnet restore ./src/Sokol.sln --verbosity m
 - dotnet build ./src/Sokol.Graphics/Sokol.Graphics.csproj --no-restore -c Release
 - dotnet build ./src/Sokol.Graphics.Tests/Sokol.Graphics.Tests.csproj --no-restore --verbosity m -c Debug
 - dotnet test ./src/Sokol.Graphics.Tests/Sokol.Graphics.Tests.csproj  --no-build --verbosity n -c Debug