version: '1.0.0.{build}'
image:
- Visual Studio 2017 
- Visual Studio 2019
- Ubuntu1604
- Ubuntu1804
branches:
  only:
  - master
skip_tags: true
cache:
  - packages -> **\packages.config
  - '%LocalAppData%\NuGet\Cache'
  - '%LocalAppData%\NuGet\v3-cache'
# nuget:
#   # account_feed: true
#   # project_feed: true
#   disable_publish_on_pr: true
#   publish_wap_octopus: true   
platform: x64
configuration: Release
init:
  - cmd: git config --global core.autocrlf true
install:
before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore ./src/Sokol.sln --verbosity m
build_script:
  - cmd: dotnet publish ./src/Sokol.sln --no-restore -c Release
after_build:
# artifacts:
#  - path: '/src/Sokol.Graphics/bin/Release/netcoreapp3.0/publish'
#    name: WebSite
#    type: WebDeployPackage
clone_depth: 1
test_script:
  - cmd: dotnet restore ./src/Sokol.sln --verbosity m
  - cmd: dotnet test ./src/Sokol.sln
on_finish :
deploy:
  - provider: GitHub
    artifact: /.*\.nupkg/           # upload all NuGet packages to release assets
    draft: false
    prerelease: false
    on:
      branch: master                # release from master branch only
      APPVEYOR_REPO_TAG: true       # deploy on tag push only