version: '1.0.0.{build}'
image:
- Visual Studio 2019
- Ubuntu1604
- Ubuntu1804
branches:
  only:
  - master
init:
  - cmd: git config --global core.autocrlf true
install:
before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore ./src/Sokol.sln --verbosity m
build_script:
  - cmd: dotnet publish ./src/Sokol.Graphics/Sokol.Graphics.csproj --no-restore -c Release
after_build:
shallow_clone: true
test_script:
  - cmd: dotnet restore ./src/Sokol.sln --verbosity m
  - cmd: dotnet test ./src/Sokol.sln
on_finish :
deploy: off