version: '1.0.0.{build}'
image:
- Visual Studio 2019
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
branches:
  only:
  - master
init:
  - cmd: git config --global core.autocrlf true
install:
before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore ./src/Sokol.sln --verbosity m
build_script:
  - cmd: dotnet publish ./src/Sokol.Graphics/Sokol.Graphics.csproj --no-restore -c Release
after_build:
shallow_clone: true
before_test:
  - cmd: dotnet restore ./src/Sokol.sln --verbosity m
  - cmd: dotnet build ./src/Sokol.sln --no-restore --verbosity m -c Debug
test_script:
  - cmd: dotnet test ./src/Sokol.sln --no-build --verbosity n -c Debug
on_finish :
deploy: off