trigger:
- master

pool:
  vmImage: 'macos-latest'

variables:
  solution: '**/*.sln'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '$(solution)'
    arguments: '--verbosity m'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(solution)'
    arguments: '--no-restore --verbosity m -c Debug'
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '$(solution)'
    arguments: '--no-build --verbosity n -c Debug'