version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.0
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - checkout
      - run:
          name: Restore
          command: dotnet restore ./src/Sokol.sln --verbosity m
      - run:
          name: Build
          command: dotnet publish ./src/Sokol.Graphics/Sokol.Graphics.csproj --no-restore -c Release
      - run:
          name: Build Tests
          command: dotnet build ./src/Sokol.sln --no-restore --verbosity m -c Debug
      - run:
          name: Run Tests
          command: dotnet test ./src/Sokol.sln --no-build --verbosity m -c Debug