trigger:
- master

pool:
  vmImage: 'macos-latest'

variables:
  solution: './src/Sokol.sln'
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

stages:

- stage: 'setup'
  displayName: 'Setup'
  jobs: 
    - job: 'install_dotnet_sdk'
      displayName: 'Install .NET SDK'
      continueOnError: false 
      steps:
      - task: UseDotNet@2
        displayName: 'Use .NET Core 3 SDK'
        inputs:
          packageType: sdk
          version: 3.0.100
          installationPath: $(Agent.ToolsDirectory)/dotnet
    - job: 'clone_repo'
      displayName: 'Clone Git repository'
      continueOnError: false
      steps:
      - checkout:
        fetchDepth: 1
        submodules: true
        clean: true

- stage: 'build'
  displayName: 'Build'
  jobs:
    - job: 'restore_solution'
      displayName: 'Restore solution'
      continueOnError: false
      steps:
      - task: DotNetCoreCLI@2
        displayName: 'Restore solution'
        inputs:
          command: 'restore'
          projects: '$(solution)'
          arguments: '--verbosity m'
    - job: 'build_solution'
      displayName: 'Build Solution'
      dependsOn: 'restore_solution'
      continueOnError: false
      steps:
      - task: DotNetCoreCLI@2
        displayName: 'Build solution'
        inputs:
          command: 'build'
          projects: '$(solution)'
          arguments: '--no-restore --verbosity m -c Release'

- stage: 'test'
  displayName: 'Test'
  jobs:
    - job: 'run_tests'
      displayName: 'Run Tests'
      continueOnError: false
      steps:
      - task: DotNetCoreCLI@2 
        displayName: 'Run Tests in Solution'
        inputs:
          command: 'test'
          projects: '$(solution)'
          arguments: '--no-build --verbosity n -c Release'