name: CodeCov

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop 

jobs:
  codecov-job:
    name: CodeCov
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
