name: .NET Core

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop 

jobs:
  my-job:
    name: Test Job
    runs-on: ubuntu-latest
    steps:
    - name: Print
      env:
        MY_VAR: Hi there! My name is
        FIRST_NAME: Link
        MIDDLE_NAME: The
        LAST_NAME: Hero of Time
      run: |
        echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.
